export const DATA_REQUEST = "DATA_REQUEST"
export const DATA_SUCCESS = "DATA_SUCCESS"
export const DATA_FAIL = "DATA_FAIL"
export const CURRENT_DATA_REQUEST = "CURRENT_DATA_REQUEST"
export const CURRENT_DATA_SUCCESS = "CURRENT_DATA_SUCCESS"
export const CURRENT_DATA_FAIL = "CURRENT_DATA_FAIL"





